// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2dDRGwSNTe-qgS8QmuZ81KFtorEmnK4o',
    appId: '1:716666765997:web:5ebdf90078539b62177c24',
    messagingSenderId: '716666765997',
    projectId: 'rideshare-b1cb7',
    authDomain: 'rideshare-b1cb7.firebaseapp.com',
    storageBucket: 'rideshare-b1cb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiOLPMf_0mz8255tEmrhENvwJ6kzoglDs',
    appId: '1:716666765997:android:0f79c5d9336f4ad8177c24',
    messagingSenderId: '716666765997',
    projectId: 'rideshare-b1cb7',
    storageBucket: 'rideshare-b1cb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0tmEF8QPMTGwIp3kta85dEBsLKmqOPEI',
    appId: '1:716666765997:ios:d781560940d21437177c24',
    messagingSenderId: '716666765997',
    projectId: 'rideshare-b1cb7',
    storageBucket: 'rideshare-b1cb7.appspot.com',
    iosBundleId: 'com.example.rideshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0tmEF8QPMTGwIp3kta85dEBsLKmqOPEI',
    appId: '1:716666765997:ios:d781560940d21437177c24',
    messagingSenderId: '716666765997',
    projectId: 'rideshare-b1cb7',
    storageBucket: 'rideshare-b1cb7.appspot.com',
    iosBundleId: 'com.example.rideshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2dDRGwSNTe-qgS8QmuZ81KFtorEmnK4o',
    appId: '1:716666765997:web:e0453976e7402d34177c24',
    messagingSenderId: '716666765997',
    projectId: 'rideshare-b1cb7',
    authDomain: 'rideshare-b1cb7.firebaseapp.com',
    storageBucket: 'rideshare-b1cb7.appspot.com',
  );
}
